project:
  type: website
  output-dir: docs

website:
  title: "Emre Türkoğlu'nun Analitik Labı"
  navbar:
    search: true
    left:
      - text: Anasayfa
        href: index.qmd
      - text: Hakkımda
        href: about.qmd
      - text: Gönderilerim
        href: posts.qmd
      - text: "MUY665 Ders Çıktıları"
        menu:
          - text: Ödevler
            href: portfolyo.qmd
          - text: Proje
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/turkogluee-netizen
      - icon: twitter
        href: https://twitter.com/turkogluee-netizen
      - icon: linkedin
        href: https://linkedin.com/in/turkogluee-netizen

  sidebar:
    - title: "Çalışmalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - MUY665 - Bahar 2026" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

